export const types = {
  login: "[Auth] Login",
  logout: "[Auth] Logout",
  uiSetError: "[UI] set error",
  uiRemoveError: "[UI] remove error",
  uiStartLoading: "[UI] Start loading",
  uiFinishLoading: "[UI] Finish loading",

  notesAddNew: "[Notes] New Note",
  notesActive: "[Notes] Set Active Note",
  notesLoad: "[Notes] Load Note",
  notesUpdate: "[Notes] Update Note",
  notesFileUrl: "[Notes] Updated img url Note",
  notesDelete: "[Notes] Delete Note",
  notesLogoutClean: "[Notes] Logout Clean Note",
  notesStartLoading: "[Notes] Start loading",
  notesFinishLoading: "[Notes] Finish loading",
  noteSaveStartLoading: "[Notes] Start save loading",
  noteSaveFinishLoading: "[Notes] Start finish loading",
  notesLogoutCleaning: "[Notes] Notes logout cleaning",
};
